### PR TITLE
Add FAQ documentation

### PR DESCRIPTION
**Pull request by ferozsalam**
- Also add a short README on building the documentation
 - Make some tweaks to allow the generation of documentation from Markdown rather than ReStructured Text
 - Format the FAQ for easier readability

### CODE REVIEW

**Review by jertel — DISMISSED** [review]
Thanks for putting this together.

**Comment by jertel** [comment]
@ferozsalam Something with your change has caused the automated build/test job to fail. I can't merge it in until it passes.

**Comment by ferozsalam** [comment]
> @ferozsalam Something with your change has caused the automated build/test job to fail. I can't merge it in until it passes.

Yep, it's to do with the addition of the Markdown file, which the test job doesn't like. I'll be pushing a fix later today.

**Comment by ferozsalam** [comment]
@jertel all fixed now, thanks for the heads up.

**Review by jertel — APPROVED** [review]

**Pull request merged**
