### PR TITLE
Add alert handler to create Datadog Events

### PR DESCRIPTION
**Pull request by 3vanlock**
Create a new alerter that sends [Datadog Events via their API](https://docs.datadoghq.com/api/latest/events/#post-an-event).

### CODE REVIEW

**Comment by nsano-rururu** [comment]
@3vanlock 

I think I need to add a description of the datadog configuration to `elastalert/docs/source/ruletypes.rst`.
Since the first character is d, I think it is good to add it between command and email.

Example) 
```
Datadog
~~~~~~~

Events are limited to 4000 characters. If an event is sent that contains a message that is longer than 4000 characters, only his first 4000 characters will be displayed.

datadog_api_key: Datadog API key.

datadog_app_key: Datadog Application key.
```

**Comment by 3vanlock** [comment]
> add a description of the datadog configuration to `elastalert/docs/source/ruletypes.rst`

Done @nsano-rururu. Thanks for the structure. I added a couple of links to Datadog's own Event documentation.

**Comment by jertel** [comment]
I see some of the other alerts have unit tests. Should a test, or tests, be added for this new logic?

**Comment by 3vanlock** [comment]
Good call @jertel. I added a new test following the style of the old tests and ran it with success locally.

**Review by jertel — APPROVED** [review]

**Pull request merged**
